import os
import glob
from pathlib import Path
from typing import Dict, Any, Optional

try:
    from .utils.llm import LLMService
except ImportError:
    # Allow running directly for testing
    import sys
    sys.path.append(str(Path(__file__).parent.parent.parent))
    from agents.code_agent.utils.llm import LLMService

class CodeAgent:
    """
    Code Agent: Analyzes game code structure, performance, and portability.
    """
    
    def __init__(self, config_path: str = "config.yaml"):
        # Load config (Mock implementation for zero-dependency)
        self.config = {
            "model_name": os.environ.get("AGENT_MODEL_NAME", "gemini-1.5-flash"),
            "max_tokens": int(os.environ.get("AGENT_MAX_TOKENS", 4000)),
            "output_dir": os.environ.get("AGENT_OUTPUT_DIR", "docs"),
        }
        
        self.llm = LLMService(model=self.config["model_name"])
        self.prompts_dir = Path(__file__).parent / "prompts"
        
    def load_prompt(self, name: str) -> str:
        """Load a prompt template from file."""
        path = self.prompts_dir / f"{name}.txt"
        if not path.exists():
            # Create default prompt if missing (for resilience)
            return f"Analyze the following code for {name}:\n\n{{{{ source_code }}}}"
        return path.read_text(encoding="utf-8")
        
    def analyze(self, game_path: str) -> str:
        """
        Run full code analysis on a game file.
        Returns the path to the generated report.
        """
        game_path_obj = Path(game_path)
        if not game_path_obj.exists():
            raise FileNotFoundError(f"Game file not found: {game_path}")
            
        print(f"Reading game source: {game_path}...")
        source_code = game_path_obj.read_text(encoding="utf-8")
        
        # 1. Analyze Structure
        print("🏗️ Phase 1: Analyzing Code Structure...")
        structure_prompt = self.load_prompt("analyze_structure")
        structure_prompt = structure_prompt.replace("{{ source_code }}", source_code[:20000])
        structure_analysis = self.llm.generate(structure_prompt)
        
        # 2. Performance Audit
        print("⚡ Phase 2: Auditing Performance...")
        perf_prompt = self.load_prompt("optimize_performance")
        perf_prompt = perf_prompt.replace("{{ source_code }}", source_code[:20000])
        perf_report = self.llm.generate(perf_prompt)
        
        # 3. Mobile Support
        print("📱 Phase 3: Assessing Mobile Support...")
        mobile_prompt = self.load_prompt("mobile_support")
        mobile_prompt = mobile_prompt.replace("{{ source_code }}", source_code[:20000])
        mobile_analysis = self.llm.generate(mobile_prompt)
        
        # 4. Compile Report
        print("📝 Phase 4: Compiling Report...")
        game_name = game_path_obj.parent.name # e.g. feeding-caiso
        report_content = self._compile_report(game_name, structure_analysis, perf_report, mobile_analysis)
        
        # Save Report
        output_dir = Path(self.config["output_dir"])
        output_dir.mkdir(parents=True, exist_ok=True)
        report_path = output_dir / f"{game_name}_code_review.md"
        report_path.write_text(report_content, encoding="utf-8")
        
        print(f"✅ Code Review Saved: {report_path}")
        return str(report_path)
        
    def _compile_report(self, game_name: str, structure: str, performance: str, mobile: str) -> str:
        """Combine analysis results into a Markdown report."""
        return f"""# {game_name.replace('-', ' ').title()} - Code Review
        
> **Generated by Code Agent**
> Date: {os.environ.get('DATE', 'Today')}

---

## 🏗️ Code Structure & Architecture
{structure}

---

## ⚡ Performance Optimization Audit
{performance}

---

## 📱 Mobile & Touch Support
{mobile}

---

## 🛠️ Recommended Refactoring
1. **Apply Object Pooling** to reduce Garbage Collection during gameplay.
2. **Decouple Event Listeners** from logic for better cleanup.
3. **Implement Touch Handlers** to support mobile players.
"""

if __name__ == "__main__":
    # Test run
    import sys
    if len(sys.argv) > 1:
        agent = CodeAgent()
        agent.analyze(sys.argv[1])
    else:
        print("Usage: python agent.py <path_to_game_file>")
