import os
import sys
import json
import urllib.request
import urllib.error
from pathlib import Path
from typing import Dict, Any, Optional

class CodeAgent:
    """
    Code Agent: Analyzes game code structure, performance, and portability via Vercel API.
    """
    
    def __init__(self, output_dir: str = "docs"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        # Default to production URL if not set
        self.api_base_url = os.environ.get("VERCEL_APP_URL", "https://caisogames.vercel.app").rstrip("/")
        self.api_endpoint = f"{self.api_base_url}/api/analyze-code"
        
    def _call_api(self, code: str, analysis_type: str) -> str:
        """Call Vercel Serverless Function to analyze code."""
        payload = {
            "type": analysis_type,
            "code": code
        }
        
        try:
            req = urllib.request.Request(
                self.api_endpoint,
                data=json.dumps(payload).encode('utf-8'),
                headers={'Content-Type': 'application/json'}
            )
            with urllib.request.urlopen(req) as response:
                result = json.loads(response.read().decode('utf-8'))
                if result.get("success"):
                    return result.get("analysis", "No analysis returned.")
                else:
                    return f"API Error: {result.get('error')}"
        except urllib.error.URLError as e:
            return f"Network Error ({self.api_endpoint}): {str(e)}"
        except Exception as e:
            return f"Error: {str(e)}"

    def analyze(self, game_path: str) -> str:
        """
        Run full code analysis on a game file.
        Returns the path to the generated report.
        """
        game_path_obj = Path(game_path)
        if not game_path_obj.exists():
            raise FileNotFoundError(f"Game file not found: {game_path}")
            
        print(f"Reading game source: {game_path}...")
        source_code = game_path_obj.read_text(encoding="utf-8")
        
        # 1. Analyze Structure
        print("🏗️ Phase 1: Analyzing Code Structure (Cloud)...")
        structure_analysis = self._call_api(source_code, "structure")
        
        # 2. Performance Audit
        print("⚡ Phase 2: Auditing Performance (Cloud)...")
        perf_report = self._call_api(source_code, "performance")
        
        # 3. Mobile Support
        print("📱 Phase 3: Assessing Mobile Support (Cloud)...")
        mobile_analysis = self._call_api(source_code, "mobile")
        
        # 4. Compile Report
        print("📝 Phase 4: Compiling Report...")
        game_name = game_path_obj.parent.name # e.g. feeding-caiso
        report_content = self._compile_report(game_name, structure_analysis, perf_report, mobile_analysis)
        
        # Save Report
        report_path = self.output_dir / f"{game_name}_code_review.md"
        report_path.write_text(report_content, encoding="utf-8")
        
        print(f"✅ Code Review Saved: {report_path}")
        return str(report_path)
        
    def _compile_report(self, game_name: str, structure: str, performance: str, mobile: str) -> str:
        """Combine analysis results into a Markdown report."""
        return f"""# {game_name.replace('-', ' ').title()} - Code Review
        
> **Generated by Code Agent**
> Date: {os.environ.get('DATE', 'Today')}
> Source: Vercel Cloud API

---

## 🏗️ Code Structure & Architecture
{structure}

---

## ⚡ Performance Optimization Audit
{performance}

---

## 📱 Mobile & Touch Support
{mobile}

---

## 🛠️ Recommended Refactoring
1. **Apply Object Pooling** to reduce Garbage Collection during gameplay.
2. **Decouple Event Listeners** from logic for better cleanup.
3. **Implement Touch Handlers** to support mobile players.
"""

if __name__ == "__main__":
    if len(sys.argv) > 1:
        agent = CodeAgent()
        agent.analyze(sys.argv[1])
    else:
        print("Usage: python agent.py <path_to_game_file>")
