"""Design Agent LLM Service - extends shared LLM with design & sound mocks."""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from agents.shared.llm import LLMService as BaseLLMService


class LLMService(BaseLLMService):
    """LLM Service with Design Agent and Sound Agent mock responses."""

    def __init__(self, **kwargs):
        kwargs.setdefault("temperature", 0.7)
        super().__init__(**kwargs)

    def _generate_mock(self, prompt: str) -> str:
        """Return a plausible mock response based on the prompt type."""
        # Design Agent Mocks
        if "Identify the following elements" in prompt:
            return """
**Genre**: Casual / Arcade Feeding Game
**Core Loop**:
- **Action**: Player throws "Kawaii" food items at Caiso (the purple monster).
- **Feedback**: Caiso reacts with animated expressions (Happy/Sad/Hungry), Sound FX plays.
- **Reward**: Score increases, Caiso evolves visually, New food items unlock.
**Controls**: Mouse Click or Touch (Mobile), Spacebar (PC).
**Win/Loss**:
- **Win**: Keep Caiso fed until Evolution stage 5.
- **Loss**: Villagers (lives) reach 0 due to starvation.
**Key Entities**: Caiso (Kawaii Monster), Player (Provider), Food (Pizza, Burger, etc.), Villagers (Resource).
"""
        elif "Evaluate the difficulty" in prompt:
            return """
**Difficulty Curve**: Static/Flat.
- The game relies on speed increasing, but the code shows fixed speeds for some elements.
- **Analysis**: The hunger decay rate seems linear (`this.hunger -= 0.1`).
**Progression**:
- New foods unlock at levels 2, 3, 4, 5.
- Visually rewarding (Kawaii food art) but mechanics remain identical.
**Risk vs Reward**:
- Low risk. Missed shots have no penalty specific enough other than time loss.
- **Feedback**: The "Sad" animation provides good negative feedback, but needs gameplay consequence.
**Issues**:
- No 'Game Over' state handled robustly in some edge cases.
"""
        elif "Propose a compelling narrative" in prompt:
            return """
**Title Proposal**: "Feeding Caiso: The Hangry Monster"
**The World**: A pastel-colored island 'NomNom Land' where monsters and villagers live in harmony, as long as lunch is served on time.
**The Protagonist**: 'Chef Pixel', the royal feeder appointed to keep the guardian monster Caiso happy.
**The Conflict**: Caiso is going through a growth spurt and gets "Hangry" (Hungry + Angry). If he's not fed, he accidentally scares the villagers away!
**Flavor Text**:
- Start: "It's Lunch Time! Don't let him get Hangry!"
- Game Over: "Oh no! The villagers ran away!"
- Level Up: "Caiso is growing! New menu unlocked!"
"""
        # Sound Agent Mocks - SFX
        elif "Web Audio API" in prompt or "sound effect" in prompt.lower():
            sound_name = "buttonClick"
            if "click" in prompt.lower():
                sound_name = "buttonClick"
            elif "jump" in prompt.lower():
                sound_name = "jump"
            elif "pickup" in prompt.lower() or "item" in prompt.lower():
                sound_name = "itemPickup"
            elif "collision" in prompt.lower() or "hit" in prompt.lower():
                sound_name = "collision"
            return f'''// {sound_name} - Generated by Sound Agent
function play{sound_name.title().replace("_", "")}() {{
    const ctx = new (window.AudioContext || window.webkitAudioContext)();
    const oscillator = ctx.createOscillator();
    const gainNode = ctx.createGain();

    oscillator.connect(gainNode);
    gainNode.connect(ctx.destination);

    oscillator.type = 'sine';
    oscillator.frequency.setValueAtTime(800, ctx.currentTime);
    oscillator.frequency.exponentialRampToValueAtTime(400, ctx.currentTime + 0.1);

    gainNode.gain.setValueAtTime(0.3, ctx.currentTime);
    gainNode.gain.exponentialRampToValueAtTime(0.01, ctx.currentTime + 0.1);

    oscillator.start(ctx.currentTime);
    oscillator.stop(ctx.currentTime + 0.1);
}}
'''
        # Sound Agent Mocks - BGM
        elif "Tone.js" in prompt or "background music" in prompt.lower() or "BGM" in prompt:
            return '''// GameplayBGM - Generated by Sound Agent
// Requires: <script src="https://cdnjs.cloudflare.com/ajax/libs/tone/14.8.49/Tone.js"></script>

class GameplayBGM {
    constructor() {
        this.synth = new Tone.PolySynth(Tone.Synth).toDestination();
        this.synth.volume.value = -10;

        this.pattern = new Tone.Sequence((time, note) => {
            this.synth.triggerAttackRelease(note, "8n", time);
        }, ["C4", "E4", "G4", "B4", "C5", "B4", "G4", "E4"], "8n");
    }

    start() {
        Tone.Transport.bpm.value = 120;
        this.pattern.start(0);
        Tone.Transport.start();
    }

    stop() {
        this.pattern.stop();
        Tone.Transport.stop();
    }

    setVolume(vol) {
        this.synth.volume.value = vol;
    }
}

// Usage:
// const bgm = new GameplayBGM();
// bgm.start();
'''
        # Sound Agent Mocks - Audit
        elif "audio implementation" in prompt.lower() or "Analyze" in prompt:
            return """
## 1. Existing Audio Implementation
- Found: `AudioContext` usage in game loop
- No external sound files (.mp3, .wav) detected
- No Tone.js or Web Audio patterns found

## 2. Game Events Needing Sounds
- **Food Throw**: When player throws food at Caiso
- **Food Hit**: When food reaches Caiso
- **Caiso React**: Happy/Sad reactions
- **Score Update**: Point increases
- **Level Up**: New food unlocked
- **Game Over**: Lives depleted

## 3. Sound Gap Analysis
- NO background music
- NO UI button sounds
- NO feedback sounds for gameplay

## 4. Sound Priority List
1. `food_throw` - Core interaction feedback
2. `caiso_happy` - Positive feedback
3. `caiso_sad` - Negative feedback
4. `level_up` - Achievement notification
5. `game_over` - Game state change
"""
        return "Mock Analysis Response"


def get_llm():
    return LLMService()
