"""Sound Agent LLM Service - extends shared LLM with sound analysis mocks."""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from agents.shared.llm import LLMService as BaseLLMService


class LLMService(BaseLLMService):
    """LLM Service with Sound Agent specific mock responses."""

    def __init__(self, **kwargs):
        kwargs.setdefault("temperature", 0.7)
        super().__init__(**kwargs)

    def _generate_mock(self, prompt: str) -> str:
        """Mock responses for Sound Agent analysis."""

        # SFX generation
        if "Web Audio API" in prompt or "sound effect" in prompt.lower():
            sound_name = "buttonClick"
            if "click" in prompt.lower():
                sound_name = "buttonClick"
            elif "jump" in prompt.lower():
                sound_name = "jump"
            elif "pickup" in prompt.lower() or "item" in prompt.lower():
                sound_name = "itemPickup"
            elif "collision" in prompt.lower() or "hit" in prompt.lower():
                sound_name = "collision"
            return f'''// {sound_name} - Generated by Sound Agent
function play{sound_name.title().replace("_", "")}() {{
    const ctx = new (window.AudioContext || window.webkitAudioContext)();
    const oscillator = ctx.createOscillator();
    const gainNode = ctx.createGain();

    oscillator.connect(gainNode);
    gainNode.connect(ctx.destination);

    oscillator.type = 'sine';
    oscillator.frequency.setValueAtTime(800, ctx.currentTime);
    oscillator.frequency.exponentialRampToValueAtTime(400, ctx.currentTime + 0.1);

    gainNode.gain.setValueAtTime(0.3, ctx.currentTime);
    gainNode.gain.exponentialRampToValueAtTime(0.01, ctx.currentTime + 0.1);

    oscillator.start(ctx.currentTime);
    oscillator.stop(ctx.currentTime + 0.1);
}}
'''
        # BGM generation
        elif "Tone.js" in prompt or "background music" in prompt.lower() or "BGM" in prompt:
            return '''// GameplayBGM - Generated by Sound Agent
class GameplayBGM {
    constructor() {
        this.synth = new Tone.PolySynth(Tone.Synth).toDestination();
        this.synth.volume.value = -10;
        this.pattern = new Tone.Sequence((time, note) => {
            this.synth.triggerAttackRelease(note, "8n", time);
        }, ["C4", "E4", "G4", "B4", "C5", "B4", "G4", "E4"], "8n");
    }
    start() { Tone.Transport.bpm.value = 120; this.pattern.start(0); Tone.Transport.start(); }
    stop() { this.pattern.stop(); Tone.Transport.stop(); }
    setVolume(vol) { this.synth.volume.value = vol; }
}
'''
        # Audio audit
        elif "audio implementation" in prompt.lower() or "Analyze" in prompt:
            return """
## 1. Existing Audio Implementation
- Found: `AudioContext` usage in game loop
- No external sound files (.mp3, .wav) detected

## 2. Game Events Needing Sounds
- **Food Throw**: When player throws food
- **Food Hit**: When food reaches target
- **Score Update**: Point increases
- **Level Up**: New level unlocked
- **Game Over**: Lives depleted

## 3. Sound Gap Analysis
- NO background music
- NO UI button sounds
- NO feedback sounds for gameplay

## 4. Sound Priority List
1. `food_throw` - Core interaction feedback
2. `caiso_happy` - Positive feedback
3. `caiso_sad` - Negative feedback
4. `level_up` - Achievement notification
5. `game_over` - Game state change
"""
        return "Mock Sound Analysis Response"


def get_llm():
    return LLMService()
