import os
import glob
from pathlib import Path
from typing import Dict, Any, Optional

try:
    from .utils.llm import LLMService
except ImportError:
    # Allow running directly for testing
    import sys
    sys.path.append(str(Path(__file__).parent.parent.parent))
    from agents.design_agent.utils.llm import LLMService

class DesignAgent:
    """
    Design Agent: Analyzes game design, balance, and narrative.
    """
    
    def __init__(self, config_path: str = "config.yaml"):
        # Load config (Mock implementation for zero-dependency)
        self.config = {
            "model_name": os.environ.get("AGENT_MODEL_NAME", "gemini-1.5-flash"),
            "max_tokens": int(os.environ.get("AGENT_MAX_TOKENS", 4000)),
            "output_dir": os.environ.get("AGENT_OUTPUT_DIR", "docs"),
        }
        
        self.llm = LLMService(model=self.config["model_name"])
        self.prompts_dir = Path(__file__).parent / "prompts"
        
    def load_prompt(self, name: str) -> str:
        """Load a prompt template from file."""
        path = self.prompts_dir / f"{name}.txt"
        if not path.exists():
            raise FileNotFoundError(f"Prompt file not found: {path}")
        return path.read_text(encoding="utf-8")
        
    def analyze(self, game_path: str) -> str:
        """
        Run full design analysis on a game file.
        Returns the path to the generated report.
        """
        game_path_obj = Path(game_path)
        if not game_path_obj.exists():
            raise FileNotFoundError(f"Game file not found: {game_path}")
            
        print(f"Reading game source: {game_path}...")
        source_code = game_path_obj.read_text(encoding="utf-8")
        
        # 1. Analyze Mechanics
        print("🔍 Phase 1: Analyzing Mechanics...")
        mechanics_prompt = self.load_prompt("analyze_mechanics")
        mechanics_prompt = mechanics_prompt.replace("{{ source_code }}", source_code[:15000]) # Truncate for safety
        mechanics_analysis = self.llm.generate(mechanics_prompt)
        
        # 2. Evaluate Balance
        print("⚖️ Phase 2: Evaluating Balance...")
        balance_prompt = self.load_prompt("evaluate_balance")
        # Extract likely config section (simple heuristic: first 200 lines or search for specific keywords)
        config_snippet = source_code[:2000] # Usually config is at top
        balance_prompt = balance_prompt.replace("{{ mechanics }}", mechanics_analysis)
        balance_prompt = balance_prompt.replace("{{ config_code }}", config_snippet)
        balance_report = self.llm.generate(balance_prompt)
        
        # 3. Suggest Narrative
        print("🎭 Phase 3: Suggesting Narrative...")
        narrative_prompt = self.load_prompt("suggest_narrative")
        narrative_prompt = narrative_prompt.replace("{{ mechanics }}", mechanics_analysis)
        narrative_analysis = self.llm.generate(narrative_prompt)
        
        # 4. Compile Report
        print("📝 Phase 4: Compiling Report...")
        game_name = game_path_obj.parent.name # e.g. feeding-caiso
        report_content = self._compile_report(game_name, mechanics_analysis, balance_report, narrative_analysis)
        
        # Save Report
        output_dir = Path(self.config["output_dir"])
        output_dir.mkdir(parents=True, exist_ok=True)
        report_path = output_dir / f"{game_name}_design_review.md"
        report_path.write_text(report_content, encoding="utf-8")
        
        print(f"✅ Design Review Saved: {report_path}")
        return str(report_path)
        
    def _compile_report(self, game_name: str, mechanics: str, balance: str, narrative: str) -> str:
        """Combine analysis results into a Markdown report."""
        return f"""# {game_name.replace('-', ' ').title()} - Design Review
        
> **Generated by Design Agent**
> Date: {os.environ.get('DATE', 'Today')}

---

## 🏗️ Mechanics Analysis
{mechanics}

---

## ⚖️ Balance & Progression Audit
{balance}

---

## 🎭 Narrative Proposal (Lore Bible)
{narrative}

---

## 🚀 Next Steps (Design Agent Recommendations)
1. Review the **Balance Audit** to identify fairness issues.
2. Consider implementing the **Narrative Proposal** to enhance immersion.
3. Use `play_agent` (Future) to verify these findings in practice.
"""

if __name__ == "__main__":
    # Test run
    import sys
    if len(sys.argv) > 1:
        agent = DesignAgent()
        agent.analyze(sys.argv[1])
    else:
        print("Usage: python agent.py <path_to_game_file>")
