"""
Core data classes for Image Agent system

These dataclasses define the structure for:
- Asset requests from games
- Generated prompts
- Quality review reports
- Agent results
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


class AssetType(Enum):
    """Types of game assets that can be generated"""
    SPRITE = "sprite"
    BACKGROUND = "background"
    UI = "ui"
    ANIMATION = "animation"
    ICON = "icon"
    TILE = "tile"


class StyleType(Enum):
    """Art styles supported by the generator"""
    PIXEL_ART = "pixel_art"
    KAWAII = "kawaii"
    CHIBI = "chibi"
    CARTOON = "cartoon"
    FLAT = "flat"
    REALISTIC = "realistic"
    RETRO_8BIT = "retro_8bit"
    RETRO_16BIT = "retro_16bit"
    WATERCOLOR = "watercolor"
    MINIMALIST = "minimalist"


@dataclass
class AssetRequest:
    """
    Structured request for a game asset

    This is the input to the Image Agent system, containing all
    specifications for the desired game asset.
    """
    # Required fields
    description: str

    # Asset specifications
    asset_type: AssetType = AssetType.SPRITE
    style: StyleType = StyleType.KAWAII
    size: Tuple[int, int] = (64, 64)

    # Transparency
    transparency: bool = True

    # Optional specifications
    color_palette: Optional[List[str]] = None
    animation_frames: int = 1
    game_context: str = ""
    reference_images: List[Path] = field(default_factory=list)

    # Constraints and requirements
    constraints: Dict[str, Any] = field(default_factory=dict)
    must_have: List[str] = field(default_factory=list)
    must_not_have: List[str] = field(default_factory=list)

    # Output preferences
    output_path: Optional[Path] = None
    output_format: str = "png"

    # Metadata
    request_id: str = ""
    requester: str = ""
    priority: int = 0

    def __post_init__(self):
        """Validate and normalize the request"""
        # Convert string types to enums if needed
        if isinstance(self.asset_type, str):
            self.asset_type = AssetType(self.asset_type)
        if isinstance(self.style, str):
            self.style = StyleType(self.style)

        # Ensure size is a tuple
        if isinstance(self.size, list):
            self.size = tuple(self.size)

        # Generate request ID if not provided
        if not self.request_id:
            import hashlib
            content = f"{self.description}{self.asset_type}{self.style}{self.size}"
            self.request_id = hashlib.sha256(content.encode()).hexdigest()[:12]


@dataclass
class DetailedPrompt:
    """
    A detailed, structured prompt for image generation

    Generated by PromptGenerator from an AssetRequest
    """
    # Core prompt components
    main_prompt: str
    style_modifiers: List[str] = field(default_factory=list)
    technical_specs: str = ""
    negative_prompt: str = ""

    # Metadata
    version: int = 1
    source_request_id: str = ""
    created_at: datetime = field(default_factory=datetime.now)

    # Previous feedback (for iterations)
    previous_feedback: List[str] = field(default_factory=list)
    improvement_notes: str = ""

    @property
    def full_prompt(self) -> str:
        """Combine all components into a single prompt string"""
        parts = [self.main_prompt]

        if self.style_modifiers:
            parts.append(", ".join(self.style_modifiers))

        if self.technical_specs:
            parts.append(self.technical_specs)

        return ". ".join(parts)

    @property
    def full_prompt_with_negative(self) -> Tuple[str, str]:
        """Return both positive and negative prompts"""
        return (self.full_prompt, self.negative_prompt)


@dataclass
class TransparencyReport:
    """
    Detailed report on image transparency quality

    Generated by TransparencyChecker
    """
    # Basic checks
    has_alpha_channel: bool = False
    background_transparent: bool = False

    # Quality metrics (0.0 - 1.0)
    edge_quality: float = 0.0
    transparency_cleanliness: float = 0.0

    # Detailed analysis
    transparent_percentage: float = 0.0
    opaque_percentage: float = 0.0
    semi_transparent_percentage: float = 0.0

    # Issues found
    artifacts: List[str] = field(default_factory=list)
    edge_issues: List[str] = field(default_factory=list)

    # Recommendations
    recommendation: str = ""

    @property
    def score(self) -> float:
        """Calculate overall transparency score"""
        if not self.has_alpha_channel:
            return 0.0

        scores = []

        # Background transparency (most important)
        if self.background_transparent:
            scores.append(1.0)
        else:
            scores.append(0.0)

        # Edge quality
        scores.append(self.edge_quality)

        # Cleanliness
        scores.append(self.transparency_cleanliness)

        return sum(scores) / len(scores) if scores else 0.0


@dataclass
class QualityReport:
    """
    Comprehensive quality review report

    Generated by QualityReviewer after analyzing a generated image
    """
    # Overall assessment
    overall_score: float = 0.0
    passed: bool = False

    # Individual scores (0.0 - 1.0)
    transparency_score: float = 0.0
    size_score: float = 0.0
    style_score: float = 0.0
    color_score: float = 0.0
    quality_score: float = 0.0
    game_fit_score: float = 0.0

    # Detailed sub-reports
    transparency_report: Optional[TransparencyReport] = None

    # Issues and feedback
    issues: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    suggestions: List[str] = field(default_factory=list)

    # What's good
    strengths: List[str] = field(default_factory=list)

    # Metadata
    iteration: int = 1
    review_time: datetime = field(default_factory=datetime.now)
    reviewer_notes: str = ""

    # Weights used for calculation
    weights: Dict[str, float] = field(default_factory=lambda: {
        'transparency': 0.20,
        'size': 0.10,
        'style': 0.25,
        'color': 0.15,
        'quality': 0.20,
        'game_fit': 0.10,
    })

    def calculate_overall_score(self) -> float:
        """Calculate weighted overall score"""
        w = self.weights
        score = (
            self.transparency_score * w['transparency'] +
            self.size_score * w['size'] +
            self.style_score * w['style'] +
            self.color_score * w['color'] +
            self.quality_score * w['quality'] +
            self.game_fit_score * w['game_fit']
        )
        self.overall_score = score
        self.passed = score >= 0.9
        return score

    def get_feedback_for_improvement(self) -> List[str]:
        """Generate actionable feedback for prompt improvement"""
        feedback = []

        # Prioritize by score (lowest first)
        scores = [
            ('transparency', self.transparency_score),
            ('size', self.size_score),
            ('style', self.style_score),
            ('color', self.color_score),
            ('quality', self.quality_score),
            ('game_fit', self.game_fit_score),
        ]
        scores.sort(key=lambda x: x[1])

        for category, score in scores:
            if score < 0.9:
                feedback.append(f"Improve {category} (current: {score*100:.0f}%)")

        feedback.extend(self.issues)
        feedback.extend(self.suggestions)

        return feedback


@dataclass
class IterationRecord:
    """
    Record of a single iteration in the generation loop

    Stored for debugging and learning purposes
    """
    iteration: int
    prompt: DetailedPrompt
    image_path: Optional[Path] = None
    image_data: Optional[bytes] = None
    review: Optional[QualityReport] = None

    # Timing
    prompt_generation_time: float = 0.0
    image_generation_time: float = 0.0
    review_time: float = 0.0

    @property
    def total_time(self) -> float:
        """Total time for this iteration"""
        return (
            self.prompt_generation_time +
            self.image_generation_time +
            self.review_time
        )

    @property
    def score(self) -> float:
        """Get the score from this iteration"""
        if self.review:
            return self.review.overall_score
        return 0.0


@dataclass
class AgentResult:
    """
    Final result from the Image Agent

    Contains the best image, all history, and comprehensive reporting
    """
    # Success indicator
    success: bool = False

    # Final output
    final_image_path: Optional[Path] = None
    final_image_data: Optional[bytes] = None
    final_score: float = 0.0

    # Generation details
    iterations: int = 0
    max_iterations_reached: bool = False

    # History (all iterations)
    history: List[IterationRecord] = field(default_factory=list)

    # Best iteration (not necessarily the last)
    best_iteration: int = 0

    # Original request
    original_request: Optional[AssetRequest] = None

    # Timing
    total_time: float = 0.0

    # Error info (if failed)
    error: Optional[str] = None

    def get_best_image(self) -> Optional[bytes]:
        """Get the image data from the best iteration"""
        if self.history and 0 <= self.best_iteration < len(self.history):
            return self.history[self.best_iteration].image_data
        return self.final_image_data

    def get_improvement_summary(self) -> str:
        """Generate a summary of score improvements across iterations"""
        if not self.history:
            return "No iterations recorded"

        scores = [h.score for h in self.history]
        lines = ["Score progression:"]
        for i, score in enumerate(scores, 1):
            status = "PASS" if score >= 0.9 else "FAIL"
            lines.append(f"  Iter {i}: {score*100:.1f}% [{status}]")

        if len(scores) > 1:
            improvement = scores[-1] - scores[0]
            lines.append(f"  Total improvement: {improvement*100:+.1f}%")

        return "\n".join(lines)
